# permissions for end users to edit valssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valssecret-editor-role
rules:
- apiGroups:
  - digitalis.io
  resources:
  - valssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - digitalis.io
  resources:
  - valssecrets/status
  verbs:
  - get
