# permissions for end users to view valssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valssecret-viewer-role
rules:
- apiGroups:
  - digitalis.io
  resources:
  - valssecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - digitalis.io
  resources:
  - valssecrets/status
  verbs:
  - get
