apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: valssecret-sample
spec:
  name: my-secret
  ttl: 3600
  data:
    username:
      ref: ref+vault://secret/mycreds/username
      encoding: text
    password:
      ref: ref+vault://secret/mycreds/password
      encoding: text
